name: learn-github-actions
on: [push]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: actions/checkout@v3
      - name: run
        env:
          MY_SECRET: {{ Docker.MY_SECRET }}
        run: |
          ls -ahl
          pwd
          go version
          echo $MY_SECRET