name: learn-github-actions
on: [push]

jobs:
  check-links:
    environment: 
      name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: actions/checkout@v3
      - name: run
        run: |
          ls -ahl
          pwd
          go version
          echo $MY_SECRET