name: learn-github-actions
on: [push]

jobs:
  check-links:
    runs-on: golang-1.20-rc-bullseye
    steps:
      - name: testing
        uses: actions/checkout@v3
      - name: run
        run: |
          ls -ahl
          pwd