name: learn-github-actions
on: [push]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: actions/checkout@v3
        run: |
          ls -ahl
          pwd