name: learn-github-actions
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
      - name: testing
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.18
      - name: Check Go Version
        env:
          - MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          go version
          pwd
          ls -ahl
          go run main.go
          echo $MY_SECRET