name: learn-github-actions
on: [push]

jobs:
  check-links:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
      - name: testing
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.18
      - name: Check Go Version
        run: |
          go version